# Generated by Django 2.0.7 on 2018-07-27 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180727_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_received',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
