# Generated by Django 2.0.7 on 2018-07-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180728_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='pspadapter',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
