# Generated by Django 2.0.7 on 2018-07-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pspadapter_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentserviceprovider',
            name='fullname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='pspadapter',
            unique_together={('psp', 'port')},
        ),
    ]
