# Generated by Django 2.0.7 on 2018-07-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180728_1055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saasinstance',
            unique_together={('fullname', 'url')},
        ),
    ]
